language: ruby
cache: bundler
os:
  - linux
  - osx
rvm:
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - 1.9.3
env:
  - DB=sqlite
  - DB=postgres
before_script:
  - sudo -u postgres createuser xylem -s
  - sudo -u postgres psql -c "ALTER USER xylem WITH PASSWORD 'xylem-secret';"
  - sudo -u postgres createdb -O xylem xylem_test
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - sqlite3
